import {CURRENCIES_SYMBOL, CURRENCY_LIST} from '@mugan86/ng-shop-ui'

export const CURRENCY_SELECT = CURRENCIES_SYMBOL[CURRENCY_LIST.PERUVIAN_SOL];
export const CURRENCY_CODE = CURRENCY_LIST.PERUVIAN_SOL;

export const REDIRECTS_ROUTES = [
  '/checkout'
]
